// Roster: four ksatria from the Mahabharata as told in Javanese wayang kulit.
// Numbers are multipliers against the base move table in fighter.js.

export const CHARACTERS = [
  {
    id: 'arjuna',
    name: 'ARJUNA',
    aksara: 'ꦄꦂꦗꦸꦤ',
    title: 'Ksatria Panengah Pandawa',
    scale: 1.0,
    hp: 1000,
    power: 1.0,
    speed: 1.05,
    jump: 1.0,
    reach: 1.08,
    frameMul: 1.0,
    trait: 'Jangkauan panjang — pukulan & tendangan menjangkau lebih jauh.',
    stats: { Kekuatan: 3, Kecepatan: 3, Ketahanan: 3, Jangkauan: 5 },
    look: {
      skin: '#d9a548', face: '#16100c', gold: '#f0c75e', cloth: '#7a2a17', cloth2: '#e9d7ad',
      pants: '#1d3f5a', accent: '#b8261a', hair: '#0d0a08',
      faceStyle: 'refined', crown: 'supit', kain: 'parang', torso: 'noble', build: 1.0,
    },
    ult: {
      type: 'pasopati', name: 'PANAH PASOPATI', aksara: 'ꦥꦱꦺꦴꦥꦠꦶ',
      desc: 'Panah bulan sabit dari Batara Guru melesat menembus layar.',
      color: 0x8fe8ff,
    },
  },
  {
    id: 'bima',
    name: 'BIMA',
    aksara: 'ꦧꦶꦩ',
    title: 'Werkudara, Sang Panegak Pandawa',
    scale: 1.14,
    hp: 1150,
    power: 1.2,
    speed: 0.84,
    jump: 0.88,
    reach: 1.05,
    frameMul: 1.08,
    armored: true,
    trait: 'Pukulan berat (maju+P) menahan satu serangan tanpa goyah.',
    stats: { Kekuatan: 5, Kecepatan: 2, Ketahanan: 5, Jangkauan: 3 },
    look: {
      skin: '#17120f', face: '#17120f', gold: '#f2c55a', cloth: 'poleng', cloth2: '#ffffff',
      pants: '#6b1a12', accent: '#c3261a', hair: '#0b0806',
      faceStyle: 'strong', crown: 'minangkara', kain: 'poleng', torso: 'mighty', build: 1.18, claw: true,
    },
    ult: {
      type: 'pancanaka', name: 'KUKU PANCANAKA', aksara: 'ꦥꦤ꧀ꦕꦤꦏ',
      desc: 'Menerjang dengan kuku sakti, mencabik lalu membanting lawan.',
      color: 0xff5a2a,
    },
  },
  {
    id: 'gatotkaca',
    name: 'GATOTKACA',
    aksara: 'ꦒꦠꦺꦴꦠ꧀ꦏꦕ',
    title: 'Otot Kawat Balung Wesi',
    scale: 1.07,
    hp: 1020,
    power: 1.07,
    speed: 0.98,
    jump: 1.22,
    reach: 1.0,
    frameMul: 1.0,
    doubleJump: true,
    trait: 'Terbang: bisa melompat dua kali di udara.',
    stats: { Kekuatan: 4, Kecepatan: 3, Ketahanan: 4, Jangkauan: 3 },
    look: {
      skin: '#c48c3e', face: '#18110d', gold: '#f5cd62', cloth: '#8e1f14', cloth2: '#f0c75e',
      pants: '#2b2b52', accent: '#7a1410', hair: '#0b0806', vest: '#6d120c',
      faceStyle: 'strong', crown: 'makutha', kain: 'cinde', torso: 'vest', build: 1.08,
    },
    ult: {
      type: 'brajamusti', name: 'AJI BRAJAMUSTI', aksara: 'ꦧꦿꦗꦩꦸꦱ꧀ꦠꦶ',
      desc: 'Melesat ke langit lalu menghantam bumi dengan tinju petir.',
      color: 0xb48cff,
    },
  },
  {
    id: 'srikandi',
    name: 'SRIKANDI',
    aksara: 'ꦱꦿꦶꦏꦤ꧀ꦝꦶ',
    title: 'Senapati Putri Pandawa',
    scale: 0.96,
    hp: 900,
    power: 0.92,
    speed: 1.2,
    jump: 1.08,
    reach: 1.0,
    frameMul: 0.86,
    nimble: true,
    trait: 'Gesit — jurus lebih cepat, guling lebih jauh.',
    stats: { Kekuatan: 2, Kecepatan: 5, Ketahanan: 2, Jangkauan: 4 },
    look: {
      skin: '#e8c07a', face: '#e8c07a', gold: '#f3cf6b', cloth: '#1f5f4f', cloth2: '#e7cf8a',
      pants: '#6a1f3d', accent: '#c23b5a', hair: '#0d0a08', kemben: '#1f5f4f',
      faceStyle: 'putri', crown: 'keling', kain: 'kawung', torso: 'putri', build: 0.9,
    },
    ult: {
      type: 'hujanpanah', name: 'HUJAN PANAH', aksara: 'ꦲꦸꦗꦤ꧀ꦥꦤꦃ',
      desc: 'Seribu anak panah dilepas ke langit dan menghujani lawan.',
      color: 0xffc46a,
    },
  },
];

export const byId = (id) => CHARACTERS.find((c) => c.id === id);
